<! name='Vehicle' desc='汽车配件信息' !>

<ConstantClass id='1' desc='常量类型' primary_key='class_id' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	class_id	类型ID	int32_t	1
#	class_name	类型名称	char	24
#	class_descr	类型描述	char	28
</ConstantClass>

<ConstantValue id='2' desc='常量值' primary_key='class_id,value' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	class_id	类型ID	int32_t	1
#	value	值	int32_t	1
#	descr	描述	char	40
</ConstantValue>

<Brand id='3' desc='品牌' primary_key='brand_code' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	brand_id	品牌ID	int32_t	1
#	brand_code	品牌编码	char	16
#	brand_name_cn	品牌中文名称	char	16
#	brand_name_en	品牌英文名称	char	20
</Brand>

<Series id='4' desc='车系' primary_key='series_id' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	series_id	车系ID	int32_t	1
#	brand_id	品牌ID	int32_t	1
#	series_name_cn	车系中文名称	char	24
#	series_name_en	车系英文名称	char	24
</Series>

<Manufacturer id='5' desc='厂家' primary_key='manu_name' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	manu_id	厂家ID	int32_t	1
#	manu_name	厂家名称	char	20
#	import	国产合资进口	uint16_t	1
#	country	国别	char	14
</Manufacturer>

<Engine id='6' desc='发动机' primary_key='engine_code' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	engine_id	发动机ID	int32_t	1
#	engine_code	发动机型号	char	14
#	cylinder_volume	气缸容积	uint16_t	1
#	displacement	排量(升)	float	1
#	intake_charge_type	进气形式	uint8_t	1
#	fuel_type	燃油类型	uint8_t	1
#	fuel_grade	燃油标号	uint8_t	1
#	cylinder_align	气缸排列形式	uint8_t	1
#	cylinder_num	气缸数(个)	uint8_t	1
#	valve_num	每缸气门数(个)	uint8_t	1
#	fuel_system_type	供油方式	uint8_t	1
</Engine>

<Model id='7' desc='车型' primary_key='model_code' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	model_id	车型ID	int32_t	1
#	series_id	车系ID	int32_t	1
#	manu_id	厂家ID	int32_t	1
#	engine_id	发动机ID	int32_t	1
#	model_code	车型编码	char	20
#	model_name	车型名称	char	32
#	chassis	代号/底盘号	char	16
#	msrp	指导价格(万元)	float	1
#	compression_ratio	压缩比	float	1
#	fuel_economy_mix	工信部综合油耗(l)	float	1
#	fuel_economy_urb	市区工况油耗	float	1
#	fuel_economy_suburb	市郊工况油耗	float	1
#	acc_time	加速时间(0-100km/h)	float	1
#	min_turn_radius	最小转弯半径	float	1
#	model_year	年款	uint16_t	1
#	max_horsepower	最大马力(ps)	uint16_t	1
#	max_power	最大功率(kw)	uint16_t	1
#	max_rpm	最大功率转速(rpm)	uint16_t	1
#	max_rpm2	最大功率转速上限(rpm)	uint16_t	1
#	max_torque	最大扭矩(n·m)	uint16_t	1
#	max_torque_rpm	最大扭矩转速(rpm)	uint16_t	1
#	max_torque_rpm2	最大扭矩转速上限(rpm)	uint16_t	1
#	max_speed	最高车速(km/h)	uint16_t	1
#	min_grd_clearance	最小离地间隙(mm)	uint16_t	1
#	length	长(mm)	uint16_t	1
#	width	宽(mm)	uint16_t	1
#	height	高(mm)	uint16_t	1
#	wheelbase	轴距(mm)	uint16_t	1
#	front_track	前轮距(mm)	uint16_t	1
#	rear_track	后轮距(mm)	uint16_t	1
#	curb_weight	整备质量(kg)	uint16_t	1
#	gross_weight	最大载重质量(kg)	uint16_t	1
#	fuel_tank_cap	油箱容积(l)	uint16_t	1
#	cargo_cap	行李厢容积(l)	uint16_t	1
#	cargo_cap2	行李厢容积上限(l)	uint16_t	1
#	year_make	生产年份	uint16_t	1
#	year_stop	停产年份	uint16_t	1
#	year_start	上市年份	uint16_t	1
#	month_start	上市月份	uint8_t	1
#	emiss_stand	排放标准	uint8_t	1
#	vehicle_type	车辆类型	uint8_t	1
#	vehicle_level	车辆级别	uint8_t	1
#	product_stat	生产状态	uint8_t	1
#	sale_stat	销售状态	uint8_t	1
#	tran_desc	变速器描述	uint8_t	1
#	gears_num	档位数	uint8_t	1
#	front_brake_type	前制动器类型	uint8_t	1
#	rear_brake_type	后制动器类型	uint8_t	1
#	front_suspension_type	前悬挂类型	uint8_t	1
#	rear_suspension_type	后悬挂类型	uint8_t	1
#	steering_type	转向机形式	uint8_t	1
#	steering_aid_type	助力类型	uint8_t	1
#	engine_position	发动机位置	uint8_t	1
#	drive_mode	驱动方式	uint8_t	1
#	body	车身型式	uint8_t	1
#	door_num	车门数	uint8_t	1
#	seat_num	座位数(个)	uint8_t	1
#	num_speaker 	扬声器数量	uint8_t	1
#	front_tire_spec	前轮胎规格	uint8_t	1
#	rear_tire_spec	后轮胎规格	uint8_t	1
#	front_rim_spec	前轮毂规格	uint8_t	1
#	rear_rim_spec	后轮毂规格	uint8_t	1
#	rim_mat	轮毂材料	uint8_t	1
#	spare_tire_spec	备胎规格	uint8_t	1
</Model>

<EPCModel id='8' desc='EPC车型' primary_key='epc_model_code' category='Yun'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	epc_model_id	车型ID	int32_t	1
#	brand_id	品牌ID	int32_t	1
#	epc_model_code	车型编码	char	16
#	epc_model_name	车型名称	char	32
</EPCModel>

<ModelTransfer id='9' desc='车型转换' primary_key='model_code' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	model_id	车型ID	int32_t	1
#	model_code	车型编码	char	20
#	epc_model_id	车型ID	int32_t	1
#	epc_model_code	EPC车型编码	char	16
</ModelTransfer>

<OE id='10' desc='原厂件' primary_key='oe_code,brand_id' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	oe_id	原厂件ID	int32_t	1
#	brand_id	品牌ID	int32_t	1
//#	manu_id	厂家ID	int32_t	1
#	oe_code	原厂件编码	char	24
//#	oe_code_trim	原厂件短编码	char	20
#	oe_name	原厂件名称	char	64
#	info	附加信息	char	48
#	price_4s	4S店价格	double	1
#	key_word	搜索词	char	64
</OE>

<AM id='11' desc='品牌件' primary_key='am_code,brand_id' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	am_id	品牌件ID	int32_t	1
#	brand_id	品牌ID	int32_t	1
//#	manu_id	厂家ID	int32_t	1
#	am_code	品牌件编码	char	24
//#	am_code_trim	品牌件短编码	char	20
#	am_name	品牌件名称	char	64
//#	image_url	产品图片url	char	80
//#	image_num	产品图片编号	int32_t	1
</AM>

<PartLink id='12' desc='配件关系' primary_key='left_id,right_id' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	left_id	配件ID	int32_t	1
#	right_id	配件ID	int32_t	1
#	relation	关系	int32_t	1
</PartLink>

<OE2Model id='13' desc='原厂件2车型' primary_key='oe_id,epc_model_id,option_code' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	oe_id	原厂件ID	int32_t	1
#	epc_model_id	车型ID	int32_t	1
#	option_code	选项码	char	160
//#	image_url	产品图片url	char	80
//#	image_num	产品图片编号	int32_t	1
</OE2Model>

<Catalog id='14' desc='目录' primary_key='cat_id' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	cat_id	目录ID	int32_t	1
#	parent_cat_id	父目录ID	int32_t	1
#	cat_name	目录名称	char	48
#	sort_order	次序	int32_t	1
#	key_word	搜索词	char	124
</Catalog>

<OE2Catalog id='15' desc='配件目录' primary_key='oe_id,cat_id' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	oe_id	原厂件ID	int32_t	1
#	cat_id	目录编号	int32_t	1
</OE2Catalog>

<VIN2Model id='16' desc='VIN查询' primary_key='vin' category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	vin	VIN号	char	20
#	model_id	车型ID	int32_t	1
#	option_code	选项码	char	200
</VIN2Model>

<LevelModelData id='17' desc='力洋车型原数据' primary_key='code' category='Level'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	code	车型编码	char	20
#	manu	厂家	char	20
#	brand	品牌	char	20
#	series	车系	char	20
#	model	车型	char	56
#	chassis	代号/底盘号	char	16
#	sale_name	销售名称	char	40
#	variant	销售版本	char	20
#	sale_name_ah	销售名称(汽车之家)	char	40
#	text1	车型文本1	char	20
#	text2	车型文本2	char	40
#	model_year	年款	uint16_t	1
#	emiss_stand	排放标准	char	10
#	vehicle_type	车辆类型	char	12
#	vehicle_level	车辆级别	char	12
#	msrp	指导价格(万元)	float	1
#	year_start	上市年份	uint16_t	1
#	month_start	上市月份	uint8_t	1
#	year_make	生产年份	uint16_t	1
#	year_stop	停产年份	uint16_t	1
#	product_stat	生产状态	char	8
#	sale_stat	销售状态	char	8
#	country	国别	char	16
#	import	国产合资进口	char	8
#	engine	发动机型号	char	18
#	cylinder_volume	气缸容积	uint16_t	1
#	displacement	排量(升)	float	1
#	intake_charge_type	进气形式	char	20
#	fuel_type	燃油类型	char	12
#	fuel_grade	燃油标号	uint8_t	1
#	max_horsepower	最大马力(ps)	uint16_t	1
#	max_power	最大功率(kw)	uint16_t	1
#	max_rpm	最大功率转速(rpm)	char	12
#	max_torque	最大扭矩(n·m)	uint16_t	1
#	max_torque_rpm	最大扭矩转速(rpm)	char	12
#	cylinder_align	气缸排列形式	char	4
#	cylinder_num	气缸数(个)	uint8_t	1
#	valve_num	每缸气门数(个)	uint8_t	1
#	compression_ratio	压缩比	float	1
#	fuel_system_type	供油方式	char	12
#	fuel_economy_mix	工信部综合油耗(l)	float	1
#	fuel_economy_urb	市区工况油耗	float	1
#	fuel_economy_suburb	市郊工况油耗	float	1
#	acc_time	加速时间(0-100km/h)	float	1
#	max_speed	最高车速(km/h)	uint16_t	1
#	tran_type	变速箱类型	char	8
#	tran_desc	变速器描述	char	20
#	gears_num	档位数	uint8_t	1
#	front_brake_type	前制动器类型	char	20
#	rear_brake_type	后制动器类型	char	20
#	front_suspension_type	前悬挂类型	char	40
#	rear_suspension_type	后悬挂类型	char	40
#	steering_type	转向机形式	char	12
#	steering_aid_type	助力类型	char	16
#	min_grd_clearance	最小离地间隙(mm)	uint16_t	1
#	min_turn_radius	最小转弯半径	float	1
#	engine_position	发动机位置	char	8
#	drive_mode	驱动方式	char	12
#	drive_type	驱动形式	char	12
#	body	车身型式	char	8
#	length	长(mm)	uint16_t	1
#	width	宽(mm)	uint16_t	1
#	height	高(mm)	uint16_t	1
#	wheelbase	轴距(mm)	uint16_t	1
#	front_track	前轮距(mm)	uint16_t	1
#	rear_track	后轮距(mm)	uint16_t	1
#	curb_weight	整备质量(kg)	uint16_t	1
#	gross_weight	最大载重质量(kg)	uint16_t	1
#	fuel_tank_cap	油箱容积(l)	uint16_t	1
#	cargo_cap	行李厢容积(l)	char	20
#	door_num	车门数	char	8
#	seat_num	座位数(个)	uint8_t	1
#	num_speaker 	扬声器数量	uint8_t	1
#	front_tire_spec	前轮胎规格	char	20
#	rear_tire_spec	后轮胎规格	char	20
#	front_rim_spec	前轮毂规格	char	20
#	rear_rim_spec	后轮毂规格	char	20
#	rim_mat	轮毂材料	char	12
#	spare_tire_spec	备胎规格	char	12
#	drivers_airbag	驾驶座安全气囊	char	8
#	passenger_airbag	副驾驶安全气囊	char	8
#	front_side_airbag	前排侧气囊	char	8
#	rear_side_airbag	后排侧气囊	char	8
#	front_head_airbag	前排头部气囊(气帘)	char	8
#	rear_head_airbag	后排头部气囊(气帘)	char	8
#	knee_airbag	膝部气囊	char	8
#	tpms	胎压监测装置	char	8
#	rsc	零胎压继续行驶	char	8
#	sbr	安全带未系提示	char	8
#	isofix	isofix儿童座椅接口	char	8
#	latch	latch座椅接口	char	8
#	immobilizer	发动机电子防盗	char	8
#	central_lock	中控锁	char	8
#	rke	遥控钥匙	char	8
#	peps	无钥匙启动系统	char	8
#	abs	abs防抱死	char	8
#	ebd	制动力分配(ebd/cbc等)	char	8
#	eba	刹车辅助(eba/bas/ba等)	char	8
#	tcs	牵引力控制(asr/tcs/trc等)	char	8
#	esp	车身稳定控制(esp/dsc/vsc等)	char	8
#	epb	自动驻车/上坡辅助	char	8
#	hdc	陡坡缓降	char	8
#	avs	可变悬挂	char	8
#	air_suspension	空气悬挂	char	8
#	variable_ratio_steering 	可变转向比	char	8
#	blis	并线辅助	char	8
#	autobrake	主动刹车	char	8
#	afs	主动转向系统	char	8
#	leather_steering_wheel	真皮方向盘	char	8
#	steering_wheel_adjust	方向盘上下调节	char	8
#	steering_wheel_adjust2	方向盘前后调节	char	8
#	steering_wheel_electric_regulation	方向盘电动调节	char	8
#	mfw	多功能方向盘	char	8
#	steering_wheel_gearshift	方向盘换挡	char	8
#	leather_seats	真皮座椅	char	8
#	sports_seats 	运动座椅	char	8
#	seat_height_adjust	座椅高低调节	char	8
#	lumbar_support_adjust	腰部支撑调节	char	8
#	shoulder_support_adjust	肩部支撑调节	char	8
#	drivers_esa	驾驶座座椅电动调节	char	8
#	passenger_esa	副驾驶座座椅电动调节	char	8
#	second_row_backrest_adjust	第二排靠背角度调节	char	8
#	second_row_move	第二排座椅移动	char	8
#	rear_esa	后排座椅电动调节	char	8
#	seat_position_memory 	电动座椅记忆	char	8
#	front_heated_seat	前排座椅加热	char	8
#	rear_heated_seat	后排座椅加热	char	8
#	seat_ventilate	座椅通风	char	8
#	seat_massage	座椅按摩	char	8
#	rear_seat_recline	后排座椅整体放倒	char	8
#	rear_seat_recline_part	后排座椅比例放倒	char	8
#	third_seat_row	第三排座椅	char	8
#	front_central_rest	前座中央扶手	char	8
#	rear_central_rest	后座中央扶手	char	8
#	rear_cup_shelf	后排杯架	char	8
#	ambient_lighting	车内氛围灯	char	8
#	rear_window_sunshade	后风挡遮阳帘	char	8
#	rear_side_sunshade	后排侧遮阳帘	char	8
#	sun_visor 	遮阳板化妆镜	char	8
#	electric_trunk	电动后备箱	char	8
#	sport_appearance_package	运动外观套件	char	8
#	electric_suction_door	电动吸合门	char	8
#	electric_sunroof	电动天窗	char	8
#	panoramic_sunroof	全景天窗	char	8
#	hid	氙气大灯	char	8
#	led	led大灯	char	8
#	drl	日间行车灯	char	8
#	automatic_headlights	自动头灯	char	8
#	acl	转向头灯	char	8
#	front_fog_lamp	前雾灯	char	8
#	headlight_height_adjust 	大灯高度可调	char	8
#	sra	大灯清洗装置	char	8
#	front_power_window	前电动车窗	char	8
#	rear_power_window	后电动车窗	char	8
#	anti_pinch_window	车窗防夹手功能	char	8
#	insulating_glass	隔热玻璃	char	8
#	electric_rearview_mirror	后视镜电动调节	char	8
#	heated_rearview_mirror	后视镜加热	char	8
#	auto_dimming_rearview_mirror	后视镜自动防眩目	char	8
#	electric_fold_rearview_mirror	后视镜电动折叠	char	8
#	position_memory_rearview_mirror	后视镜记忆	char	8
#	rear_wiper	后雨刷	char	8
#	sensing_wiper	感应雨刷	char	8
#	ccs	定速巡航	char	8
#	park_assist	泊车辅助	char	8
#	reverse_video_image	倒车视频影像	char	8
#	ecu_screen	行车电脑显示屏	char	8
#	hud	hud抬头数字显示	char	8
#	gps	gps导航	char	8
#	gps_is	定位互动服务	char	8
#	central_control_screen 	中控台彩色大屏	char	8
#	hmi	人机交互系统	char	8
#	built_in_disk	内置硬盘	char	8
#	bluetooth	蓝牙/车载电话	char	8
#	tv	车载电视	char	8
#	rear_lcd_screen	后排液晶屏	char	8
#	aux	外接音源接口(aux/usb/ipod等)	char	8
#	mp3	音频支持mp3	char	8
#	single_disc_cd	单碟cd	char	8
#	multi_disc_cd	多碟cd	char	8
#	virtual_multi_disc_cd	虚拟多碟cd	char	8
#	single_disc_dvd	单碟dvd	char	8
#	multi_disc_dvd	多碟dvd	char	8
#	ac	空调	char	8
#	thermatic	自动空调	char	8
#	rear_ac	后排独立空调	char	8
#	rear_air_outlet 	后座出风口	char	8
#	temp_zc	温度分区控制	char	8
#	pollen_filter	空气调节/花粉过滤	char	8
#	fridge	车载冰箱	char	8
#	park_assist_vision	自动泊车入位	char	8
#	nvs	夜视系统	char	8
#	splitview	中控液晶屏分屏显示	char	8
#	acc	自适应巡航	char	8
#	pancam	全景摄像头	char	8
#	parking_sensor	倒车雷达	char	8
#	telematics	车载信息服务	char	8
#	color	车身颜色	char	160
</LevelModelData>

<LevelModel id='18' desc='力洋车型' primary_key='code' category='Level'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	code	车型编码	char	20
#	manu	厂家	char	20
#	brand	品牌	char	20
#	series	车系	char	20
#	model	车型	char	56
#	chassis	代号/底盘号	char	16
#	sale_name	销售名称	char	40
#	variant	销售版本	char	20
#	sale_name_ah	销售名称(汽车之家)	char	40
#	text1	车型文本1	char	20
#	text2	车型文本2	char	40
#	country	国别	char	16
#	engine	发动机型号	char	16
#	msrp	指导价格(万元)	float	1
#	displacement	排量(升)	float	1
#	compression_ratio	压缩比	float	1
#	fuel_economy_mix	工信部综合油耗(l)	float	1
#	fuel_economy_urb	市区工况油耗	float	1
#	fuel_economy_suburb	市郊工况油耗	float	1
#	acc_time	加速时间(0-100km/h)	float	1
#	min_turn_radius	最小转弯半径	float	1
#	model_year	年款	uint16_t	1
#	cylinder_volume	气缸容积	uint16_t	1
#	max_horsepower	最大马力(ps)	uint16_t	1
#	max_power	最大功率(kw)	uint16_t	1
#	max_rpm	最大功率转速(rpm)	uint16_t	1
#	max_rpm2	最大功率转速上限(rpm)	uint16_t	1
#	max_torque	最大扭矩(n·m)	uint16_t	1
#	max_torque_rpm	最大扭矩转速(rpm)	uint16_t	1
#	max_torque_rpm2	最大扭矩转速上限(rpm)	uint16_t	1
#	max_speed	最高车速(km/h)	uint16_t	1
#	min_grd_clearance	最小离地间隙(mm)	uint16_t	1
#	length	长(mm)	uint16_t	1
#	width	宽(mm)	uint16_t	1
#	height	高(mm)	uint16_t	1
#	wheelbase	轴距(mm)	uint16_t	1
#	front_track	前轮距(mm)	uint16_t	1
#	rear_track	后轮距(mm)	uint16_t	1
#	curb_weight	整备质量(kg)	uint16_t	1
#	gross_weight	最大载重质量(kg)	uint16_t	1
#	fuel_tank_cap	油箱容积(l)	uint16_t	1
#	cargo_cap	行李厢容积(l)	uint16_t	1
#	cargo_cap2	行李厢容积上限(l)	uint16_t	1
#	year_make	生产年份	uint16_t	1
#	year_stop	停产年份	uint16_t	1
#	year_start	上市年份	uint16_t	1
#	month_start	上市月份	uint8_t	1
#	emiss_stand	排放标准	uint8_t	1
#	vehicle_type	车辆类型	uint8_t	1
#	vehicle_level	车辆级别	uint8_t	1
#	product_stat	生产状态	uint8_t	1
#	sale_stat	销售状态	uint8_t	1
#	import	国产合资进口	uint8_t	1
#	intake_charge_type	进气形式	uint8_t	1
#	fuel_type	燃油类型	uint8_t	1
#	fuel_grade	燃油标号	uint8_t	1
#	cylinder_align	气缸排列形式	uint8_t	1
#	cylinder_num	气缸数(个)	uint8_t	1
#	valve_num	每缸气门数(个)	uint8_t	1
#	fuel_system_type	供油方式	uint8_t	1
#	tran_type	变速箱类型	uint8_t	1
#	tran_desc	变速器描述	uint8_t	1
#	gears_num	档位数	uint8_t	1
#	front_brake_type	前制动器类型	uint8_t	1
#	rear_brake_type	后制动器类型	uint8_t	1
#	front_suspension_type	前悬挂类型	uint8_t	1
#	rear_suspension_type	后悬挂类型	uint8_t	1
#	steering_type	转向机形式	uint8_t	1
#	steering_aid_type	助力类型	uint8_t	1
#	engine_position	发动机位置	uint8_t	1
#	drive_mode	驱动方式	uint8_t	1
#	drive_type	驱动形式	uint8_t	1
#	body	车身型式	uint8_t	1
#	door_num	车门数	uint8_t	1
#	seat_num	座位数(个)	uint8_t	1
#	num_speaker 	扬声器数量	uint8_t	1
#	front_tire_spec	前轮胎规格	uint8_t	1
#	rear_tire_spec	后轮胎规格	uint8_t	1
#	front_rim_spec	前轮毂规格	uint8_t	1
#	rear_rim_spec	后轮毂规格	uint8_t	1
#	rim_mat	轮毂材料	uint8_t	1
#	spare_tire_spec	备胎规格	uint8_t	1
#	drivers_airbag	驾驶座安全气囊	uint8_t	1
#	passenger_airbag	副驾驶安全气囊	uint8_t	1
#	front_side_airbag	前排侧气囊	uint8_t	1
#	rear_side_airbag	后排侧气囊	uint8_t	1
#	front_head_airbag	前排头部气囊(气帘)	uint8_t	1
#	rear_head_airbag	后排头部气囊(气帘)	uint8_t	1
#	knee_airbag	膝部气囊	uint8_t	1
#	tpms	胎压监测装置	uint8_t	1
#	rsc	零胎压继续行驶	uint8_t	1
#	sbr	安全带未系提示	uint8_t	1
#	isofix	isofix儿童座椅接口	uint8_t	1
#	latch	latch座椅接口	uint8_t	1
#	immobilizer	发动机电子防盗	uint8_t	1
#	central_lock	中控锁	uint8_t	1
#	rke	遥控钥匙	uint8_t	1
#	peps	无钥匙启动系统	uint8_t	1
#	abs	abs防抱死	uint8_t	1
#	ebd	制动力分配(ebd/cbc等)	uint8_t	1
#	eba	刹车辅助(eba/bas/ba等)	uint8_t	1
#	tcs	牵引力控制(asr/tcs/trc等)	uint8_t	1
#	esp	车身稳定控制(esp/dsc/vsc等)	uint8_t	1
#	epb	自动驻车/上坡辅助	uint8_t	1
#	hdc	陡坡缓降	uint8_t	1
#	avs	可变悬挂	uint8_t	1
#	air_suspension	空气悬挂	uint8_t	1
#	variable_ratio_steering 	可变转向比	uint8_t	1
#	blis	并线辅助	uint8_t	1
#	autobrake	主动刹车	uint8_t	1
#	afs	主动转向系统	uint8_t	1
#	leather_steering_wheel	真皮方向盘	uint8_t	1
#	steering_wheel_adjust	方向盘上下调节	uint8_t	1
#	steering_wheel_adjust2	方向盘前后调节	uint8_t	1
#	steering_wheel_electric_regulation	方向盘电动调节	uint8_t	1
#	mfw	多功能方向盘	uint8_t	1
#	steering_wheel_gearshift	方向盘换挡	uint8_t	1
#	leather_seats	真皮座椅	uint8_t	1
#	sports_seats 	运动座椅	uint8_t	1
#	seat_height_adjust	座椅高低调节	uint8_t	1
#	lumbar_support_adjust	腰部支撑调节	uint8_t	1
#	shoulder_support_adjust	肩部支撑调节	uint8_t	1
#	drivers_esa	驾驶座座椅电动调节	uint8_t	1
#	passenger_esa	副驾驶座座椅电动调节	uint8_t	1
#	second_row_backrest_adjust	第二排靠背角度调节	uint8_t	1
#	second_row_move	第二排座椅移动	uint8_t	1
#	rear_esa	后排座椅电动调节	uint8_t	1
#	seat_position_memory 	电动座椅记忆	uint8_t	1
#	front_heated_seat	前排座椅加热	uint8_t	1
#	rear_heated_seat	后排座椅加热	uint8_t	1
#	seat_ventilate	座椅通风	uint8_t	1
#	seat_massage	座椅按摩	uint8_t	1
#	rear_seat_recline	后排座椅整体放倒	uint8_t	1
#	rear_seat_recline_part	后排座椅比例放倒	uint8_t	1
#	third_seat_row	第三排座椅	uint8_t	1
#	front_central_rest	前座中央扶手	uint8_t	1
#	rear_central_rest	后座中央扶手	uint8_t	1
#	rear_cup_shelf	后排杯架	uint8_t	1
#	ambient_lighting	车内氛围灯	uint8_t	1
#	rear_window_sunshade	后风挡遮阳帘	uint8_t	1
#	rear_side_sunshade	后排侧遮阳帘	uint8_t	1
#	sun_visor 	遮阳板化妆镜	uint8_t	1
#	electric_trunk	电动后备箱	uint8_t	1
#	sport_appearance_package	运动外观套件	uint8_t	1
#	electric_suction_door	电动吸合门	uint8_t	1
#	electric_sunroof	电动天窗	uint8_t	1
#	panoramic_sunroof	全景天窗	uint8_t	1
#	hid	氙气大灯	uint8_t	1
#	led	led大灯	uint8_t	1
#	drl	日间行车灯	uint8_t	1
#	automatic_headlights	自动头灯	uint8_t	1
#	acl	转向头灯	uint8_t	1
#	front_fog_lamp	前雾灯	uint8_t	1
#	headlight_height_adjust 	大灯高度可调	uint8_t	1
#	sra	大灯清洗装置	uint8_t	1
#	front_power_window	前电动车窗	uint8_t	1
#	rear_power_window	后电动车窗	uint8_t	1
#	anti_pinch_window	车窗防夹手功能	uint8_t	1
#	insulating_glass	隔热玻璃	uint8_t	1
#	electric_rearview_mirror	后视镜电动调节	uint8_t	1
#	heated_rearview_mirror	后视镜加热	uint8_t	1
#	auto_dimming_rearview_mirror	后视镜自动防眩目	uint8_t	1
#	electric_fold_rearview_mirror	后视镜电动折叠	uint8_t	1
#	position_memory_rearview_mirror	后视镜记忆	uint8_t	1
#	rear_wiper	后雨刷	uint8_t	1
#	sensing_wiper	感应雨刷	uint8_t	1
#	ccs	定速巡航	uint8_t	1
#	park_assist	泊车辅助	uint8_t	1
#	reverse_video_image	倒车视频影像	uint8_t	1
#	ecu_screen	行车电脑显示屏	uint8_t	1
#	hud	hud抬头数字显示	uint8_t	1
#	gps	gps导航	uint8_t	1
#	gps_is	定位互动服务	uint8_t	1
#	central_control_screen 	中控台彩色大屏	uint8_t	1
#	hmi	人机交互系统	uint8_t	1
#	built_in_disk	内置硬盘	uint8_t	1
#	bluetooth	蓝牙/车载电话	uint8_t	1
#	tv	车载电视	uint8_t	1
#	rear_lcd_screen	后排液晶屏	uint8_t	1
#	aux	外接音源接口(aux/usb/ipod等)	uint8_t	1
#	mp3	音频支持mp3	uint8_t	1
#	single_disc_cd	单碟cd	uint8_t	1
#	multi_disc_cd	多碟cd	uint8_t	1
#	virtual_multi_disc_cd	虚拟多碟cd	uint8_t	1
#	single_disc_dvd	单碟dvd	uint8_t	1
#	multi_disc_dvd	多碟dvd	uint8_t	1
#	ac	空调	uint8_t	1
#	thermatic	自动空调	uint8_t	1
#	rear_ac	后排独立空调	uint8_t	1
#	rear_air_outlet 	后座出风口	uint8_t	1
#	temp_zc	温度分区控制	uint8_t	1
#	pollen_filter	空气调节/花粉过滤	uint8_t	1
#	fridge	车载冰箱	uint8_t	1
#	park_assist_vision	自动泊车入位	uint8_t	1
#	nvs	夜视系统	uint8_t	1
#	splitview	中控液晶屏分屏显示	uint8_t	1
#	acc	自适应巡航	uint8_t	1
#	pancam	全景摄像头	uint8_t	1
#	parking_sensor	倒车雷达	uint8_t	1
#	telematics	车载信息服务	uint8_t	1
#	color	车身颜色	char	160
</LevelModel>

<Level2YunData id='19' desc='力洋2云车配原数据' category='Yun'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	level_code	力洋车型编码	char	20
#	yun_code	云车配车型编码	char	20
#	brand_code	品牌编码	char	16
#	name	名称	char	40
</Level2YunData>

<YunArticle id='20' desc='云车配配件' category='Yun'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	cat_id	一级目录编号	char	8
#	cat_name	一级目录名称	char	48
#	cat_id2	二级目录编号	char	8
#	cat_name2	二级目录名称	char	120
#	graph_num	图编号	char	10
#	code	零件号	char	20
#	code2	零件号-长格式	char	24
#	descr	零件描述	char	144
#	remark1	备注1	char	160
#	number	件数	uint16_t	1
#	type	型号	char	128
#	remark2	起始年	char	128
#	remark3	终止年	char	80
#	remark4	替换取消代码	char	64
#	remark5	备注5	char	32
#	remark6	左/右	char	8
#	remark7	备注7	char	8
#	remark8	备注8	char	8
#	remark9	备注9	char	12
</YunArticle>

<JMData id='21' desc='精米原数据' category='JM'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	cat_name	一级目录名称	char	40
#	cat_name2	二级目录名称	char	40
#	cat_name3	三级目录名称	char	40
#	name	零件名称	char	48
#	alias	零件别名	char	64
#	number	零件数量	int32_t	1
#	oe_name	原厂件名称	char	64
#	info	备注	char	96
</JMData>

<Vocabulary id='22' desc='分类信息' category='JM'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	cat_id	目录编号	int32_t	1
#	name	零件名称	char	48
#	alias	零件别名	char	64
#	number	零件数量	int32_t	1
#	oe_name	原厂件名称	char	64
#	info	备注	char	96
</Vocabulary>
 
<UnIdentifyOE id='23' desc='未分类OE'  category='JM'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	brand_code	品牌编码	char	16
#	oe_code	原厂件编码	char	24
#	cat_id	一级目录	char	44
#	cat2_id	二级目录	char	44
#	oe_name	原厂件名称	char	64
#	info	备注	char	64
</UnIdentifyOE>

<OEData id='24' desc='原厂件数据'  category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	oe_code	原厂件编码	char	24
#	brand	品牌	char	24
#	oe_name	原厂件名称	char	64
#	price	销售价格	double	1
</OEData>

<VendorData id='25' desc='经销商数据'  category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	code	商品编码	char	24
#	type	类别	char	16
#	brand_name_cn	品牌中文名称 	char	16
#	brand_code	品牌编码	char	16
#	name	商品名称	char	64
#	common	通用名称	char	48
#	alias	别名	char	48
#	oe_code	对应原厂件编码	char	24
#	am_code	品牌件编码	char	24
#	vehicle	车型	char	16
#	price_4s	4s店价格	double	1
#	price_cost	保值单价	double	1
#	price	销售价格	double	1
#	stock	可售库存	int32_t	1
#	sales_min	最低售量	int32_t	1
#	warranty	保质期	char	16
#	post_sale	售后周期	char	16
#	quality	品质等级	char	16
#	report	质检报告	char	16
#	unit	计量单位	char	16
#	pack_size	包装规格	char	16
#	pack_min	最小包装	char	16
#	amount	每车用量	char	16
#	weight	重量	char	16
#	volume	体积	char	16
#	dimension	长宽高	char	16
#	color	颜色	char	16
#	attention	特别提醒	char	16
</VendorData>

<ExchangeData id='26' desc='交换数据'  category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	code	商品编码	char	24
#	brand_name_cn	品牌中文名称 	char	16
#	brand_code	品牌编码	char	16
#	am_code	品牌件编码	char	24
#	name	商品名称	char	64
#	oe_code	原厂件编码	char	24
#	oe_brand_name_cn	原厂品牌中文名称 	char	16
#	oe_brand_code	原厂品牌编码 	char	16
#	vendor	供应商	char	48
#	price_4s	4S店价格	double	1
#	price	销售价格	double	1
#	stock	可售库存	int32_t	1
</ExchangeData>

<CatalogMap id='27' desc='目录映射'  category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	cat_name	一级目录名称	char	40
#	cat_name2	二级目录名称	char	40
#	cat_name3	三级目录名称	char	40
#	epc_cat_name	EPC一级目录名称	char	48
#	epc_cat_name2	EPC二级目录名称	char	48
</CatalogMap>

<NameConvert id='28' desc='名称标准化'  category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	cat_name	一级目录名称	char	40
#	cat_name2	二级目录名称	char	40
#	cat_name3	三级目录名称	char	40
#	epc_cat_name	EPC一级目录名称	char	48
#	epc_cat_name2	EPC二级目录名称	char	48
#	oe_code	原厂件编码	char	24
#	oe_name	原厂件名称	char	64
#	info	附加信息	char	32
#	vendor_name	经销商原厂件名称	char	64
#	standard_name	标准名称	char	48
</NameConvert>

<OEDataEx id='29' desc='原厂件数据扩展'  category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	oe_code	编码	char	24
#	brand	品牌	char	24
#	erp_name	ERP名称	char	48
#	tb_name	TB名称	char	48
#	join_name	JOIN名称	char	48
#	tb_price	TB销售价格	double	1
#	join_price	JOIN销售价格	double	1
</OEDataEx>

<OptionCode id='30' desc='配置项'  category='CassTime'>
@	name	desc	type	size
//	列名	描述	类型	长度
#	option_code	配置码	char	8
#	brand_id	品牌ID	int32_t	1
#	descr	配置项含义	char	48
</OptionCode>

